### ISSUE TITLE
Clarify mapping of rules to traits?

### ISSUE THREAD

**Issue by andrewd789** [ukaraoz/microtrait#10]
Hello,

Thanks for the great package. I have applied microtrait to several metagenomes. Now I wish to interpret the rules and traits detected, but I am puzzled by some aspects of this. 

I downloaded the supplementary excel tables from the microtraits publication (https://www.frontiersin.org/articles/10.3389/fbinf.2022.918853/full), to try to determine how the rules and traits matched up with one another. I see that there are 1,445 rules listed (in ST4), but only 975 rules are listed in the rules-to-traits mapping (in ST5). What explains this difference, and how can one interpret the rules not listed in the rules-to-traits mapping?

Thanks,

Andrew.

**Comment by ukaraoz** [comment]
Thanks Andrew.
The primary output of microtrait is the trait matrix, which captures a
subset of the asserted rules as you said. The other rules are there for
mostly debugging specificity/sensitivity tradeoff for those assertions.
They mostly map to the same traits in the trait matrix where the stringency
of the detection is different (i.e. more/less stringent co-occurrence of
the protein families to assert detection of a pathway).
ulas.
-------------------------
Ulas Karaoz, Ph.D.
Research Scientist
Climate and Ecosystems Sciences
Lawrence Berkeley National Laboratory

1 Cyclotron Road, Mail Stop: 70A-3317
Berkeley, CA 94720
Phone: ( <510-486-7490>510) 486 4118 (office)
***@***.***

**Comment by andrewd789** [comment]
Hi, many thanks for the explanation. I will focus on the rules represented in the rule-to-traits table then.

A.
