### ISSUE TITLE
Where are OGT, doubling time in mircoTrait output?

### ISSUE THREAD

**Issue by jlw-ecoevo** [ukaraoz/microtrait#4]
Hi! 

I've got microTrait running with no issues but I am trying to find certain output variables and the output does not quite correspond to what it says in the README (e.g., no field called "all_traits"). None of the 3 granularity matrices seem to include OGT or min doubling time? (and this causes issues with the downstream analysis code)

Thanks!
-JL

**Comment by ukaraoz** [comment]
Hi JL, thanks for letting me know, I should have made a mistake in pushing the local branch. Unfortunately, I am away  for a few weeks and won't be able to get to this till then.

**Comment by michoug** [comment]
Hi,
Any news on the implementation of these parameters in the package?
Greg

**Comment by MarineBergot** [comment]
Hi, i have the same issues than most of people here (this one + the one with parallel), an update is possible ? your package is really cool and it would be super cool to use it if you have good version then we don't need to rewrite all your code! and same the dbcan database is now in v11 but it's hard to change everything as there is no option! thanks for your work!

**Comment by bryantdo** [comment]
any update on these issues

**Comment by ukaraoz** [comment]
These (mingentime and OGT) have been refactored into the current master branch.

**Comment by ukaraoz** [comment]
These (mingentime and OGT) have been refactored into the current master branch.

**Comment by bryantdo** [comment]
Hello,

Still having this issue:

> trait_matrixatgranularity3 = genomeset_results[["trait_matrixatgranularity3"]] %>%
  dplyr::select(c("id", traits, "mingentime", "ogt")) %>%
  #dplyr::slice(1:100) %>%
  dplyr::filter(`mingentime` < 100) %>%
  dplyr::filter(!is.na(`mingentime`) & !is.na(`ogt`))
Error in `dplyr::select()`:
! Can't subset columns that don't exist.
✖ Column `mingentime` doesn't exist.

Any ideas?

**Comment by michoug** [comment]
Hi @bryantdo 
The names apparently changed to `growthrate` and `optimumT`
Best
Greg

**Comment by bryantdo** [comment]
@michoug Well thank you for that information!
